### PR TITLE
-Added Configuration File

### PR DESCRIPTION
**Pull request by CalamitousEnd**

### CODE REVIEW

**Comment by PaintNinja** [comment]
Thanks for your PR! :) Unfortunately, I can't accept it in its current state as it overwrites all files - even those without code changes. If you could fix this, that would be appreciated and I'll merge.

**Comment by CalamitousEnd** [comment]
Got it, sorry about that. This is the first time I have ever submitted a pull request. Sorry bout that.

**Comment by CalamitousEnd** [comment]
Should be fixed now. Only kept the files I needed to change.

**Comment by PaintNinja** [comment]
> Should be fixed now. Only kept the files I needed to change and the config file I added.

That's... not how pull requests work.

In simple terms, when you make a pull request and make changes, you're asking the author to do the same changes you made. In other words, if you delete something in your PR, you're asking the person to also delete those things. If you add something in your PR, you're asking them to also add those things.

I'm going to close this PR as merging it now would break the mod. I'll manually copy over the part you intended and credit you in the changelog.

**Comment by CalamitousEnd** [comment]
All right. Sorry about that mess with the Pull Requests thing. I am still pretty new to Github.

**Pull request closed without merging**
